// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// protoc        (unknown)
// source: controller.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	sync "sync"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType represents the type of node event
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED           EventType = 0
	EventType_EVENT_TYPE_NODE_ONLINE           EventType = 1
	EventType_EVENT_TYPE_NODE_OFFLINE          EventType = 2
	EventType_EVENT_TYPE_HEARTBEAT             EventType = 3
	EventType_EVENT_TYPE_NODE_INITIALIZING     EventType = 4
	EventType_EVENT_TYPE_NODE_READY            EventType = 5
	EventType_EVENT_TYPE_SERVER_CREATED        EventType = 6
	EventType_EVENT_TYPE_SERVER_STARTED        EventType = 7
	EventType_EVENT_TYPE_SERVER_STOPPED        EventType = 8
	EventType_EVENT_TYPE_SERVER_RESTARTED      EventType = 9
	EventType_EVENT_TYPE_SERVER_DELETED        EventType = 10
	EventType_EVENT_TYPE_METRICS_REPORT        EventType = 11
	EventType_EVENT_TYPE_FILE_OPERATION_RESULT EventType = 12
	EventType_EVENT_TYPE_COMMAND_RESULT        EventType = 13
)

func (e EventType) String() string {
	switch e {
	case EventType_EVENT_TYPE_NODE_ONLINE:
		return "NODE_ONLINE"
	case EventType_EVENT_TYPE_NODE_OFFLINE:
		return "NODE_OFFLINE"
	case EventType_EVENT_TYPE_HEARTBEAT:
		return "HEARTBEAT"
	case EventType_EVENT_TYPE_NODE_INITIALIZING:
		return "NODE_INITIALIZING"
	case EventType_EVENT_TYPE_NODE_READY:
		return "NODE_READY"
	case EventType_EVENT_TYPE_SERVER_CREATED:
		return "SERVER_CREATED"
	case EventType_EVENT_TYPE_SERVER_STARTED:
		return "SERVER_STARTED"
	case EventType_EVENT_TYPE_SERVER_STOPPED:
		return "SERVER_STOPPED"
	case EventType_EVENT_TYPE_SERVER_RESTARTED:
		return "SERVER_RESTARTED"
	case EventType_EVENT_TYPE_SERVER_DELETED:
		return "SERVER_DELETED"
	case EventType_EVENT_TYPE_METRICS_REPORT:
		return "METRICS_REPORT"
	case EventType_EVENT_TYPE_FILE_OPERATION_RESULT:
		return "FILE_OPERATION_RESULT"
	case EventType_EVENT_TYPE_COMMAND_RESULT:
		return "COMMAND_RESULT"
	default:
		return "UNSPECIFIED"
	}
}

// CommandType represents the type of controller command
type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED     CommandType = 0
	CommandType_COMMAND_TYPE_INITIALIZE_NODE CommandType = 1
	CommandType_COMMAND_TYPE_CREATE_SERVER   CommandType = 2
	CommandType_COMMAND_TYPE_START_SERVER    CommandType = 3
	CommandType_COMMAND_TYPE_STOP_SERVER     CommandType = 4
	CommandType_COMMAND_TYPE_RESTART_SERVER  CommandType = 5
	CommandType_COMMAND_TYPE_DELETE_SERVER   CommandType = 6
	CommandType_COMMAND_TYPE_FILE_LIST       CommandType = 10
	CommandType_COMMAND_TYPE_FILE_CREATE     CommandType = 11
	CommandType_COMMAND_TYPE_FILE_DELETE     CommandType = 12
	CommandType_COMMAND_TYPE_FILE_RENAME     CommandType = 13
	CommandType_COMMAND_TYPE_FILE_MOVE       CommandType = 14
	CommandType_COMMAND_TYPE_FILE_COPY       CommandType = 15
	CommandType_COMMAND_TYPE_FILE_WRITE      CommandType = 16
	CommandType_COMMAND_TYPE_FILE_READ       CommandType = 17
	CommandType_COMMAND_TYPE_FILE_ZIP        CommandType = 18
	CommandType_COMMAND_TYPE_FILE_UNZIP      CommandType = 19
	CommandType_COMMAND_TYPE_FILE_EXISTS     CommandType = 20
	CommandType_COMMAND_TYPE_FILE_MKDIR      CommandType = 21
)

func (c CommandType) String() string {
	switch c {
	case CommandType_COMMAND_TYPE_INITIALIZE_NODE:
		return "INITIALIZE_NODE"
	case CommandType_COMMAND_TYPE_CREATE_SERVER:
		return "CREATE_SERVER"
	case CommandType_COMMAND_TYPE_START_SERVER:
		return "START_SERVER"
	case CommandType_COMMAND_TYPE_STOP_SERVER:
		return "STOP_SERVER"
	case CommandType_COMMAND_TYPE_RESTART_SERVER:
		return "RESTART_SERVER"
	case CommandType_COMMAND_TYPE_DELETE_SERVER:
		return "DELETE_SERVER"
	case CommandType_COMMAND_TYPE_FILE_LIST:
		return "FILE_LIST"
	case CommandType_COMMAND_TYPE_FILE_CREATE:
		return "FILE_CREATE"
	case CommandType_COMMAND_TYPE_FILE_DELETE:
		return "FILE_DELETE"
	case CommandType_COMMAND_TYPE_FILE_RENAME:
		return "FILE_RENAME"
	case CommandType_COMMAND_TYPE_FILE_MOVE:
		return "FILE_MOVE"
	case CommandType_COMMAND_TYPE_FILE_COPY:
		return "FILE_COPY"
	case CommandType_COMMAND_TYPE_FILE_WRITE:
		return "FILE_WRITE"
	case CommandType_COMMAND_TYPE_FILE_READ:
		return "FILE_READ"
	case CommandType_COMMAND_TYPE_FILE_ZIP:
		return "FILE_ZIP"
	case CommandType_COMMAND_TYPE_FILE_UNZIP:
		return "FILE_UNZIP"
	case CommandType_COMMAND_TYPE_FILE_EXISTS:
		return "FILE_EXISTS"
	case CommandType_COMMAND_TYPE_FILE_MKDIR:
		return "FILE_MKDIR"
	default:
		return "UNSPECIFIED"
	}
}

// ServerState represents the state of a game server
type ServerState int32

const (
	ServerState_SERVER_STATE_UNSPECIFIED ServerState = 0
	ServerState_SERVER_STATE_STOPPED     ServerState = 1
	ServerState_SERVER_STATE_RUNNING     ServerState = 2
	ServerState_SERVER_STATE_STARTING    ServerState = 3
	ServerState_SERVER_STATE_STOPPING    ServerState = 4
	ServerState_SERVER_STATE_ERROR       ServerState = 5
)

func (s ServerState) String() string {
	switch s {
	case ServerState_SERVER_STATE_STOPPED:
		return "STOPPED"
	case ServerState_SERVER_STATE_RUNNING:
		return "RUNNING"
	case ServerState_SERVER_STATE_STARTING:
		return "STARTING"
	case ServerState_SERVER_STATE_STOPPING:
		return "STOPPING"
	case ServerState_SERVER_STATE_ERROR:
		return "ERROR"
	default:
		return "UNSPECIFIED"
	}
}

// RegisterNodeRequest represents a node registration request
type RegisterNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId         string         `json:"nodeId"`
	Hostname       string         `json:"hostname"`
	IpAddress      string         `json:"ipAddress"`
	Resources      *NodeResources `json:"resources"`
	SupportedGames []string       `json:"supportedGames"`
	OsVersion      string         `json:"osVersion"`
	AgentVersion   string         `json:"agentVersion"`
	Initialized    bool           `json:"initialized"`
	GameType       string         `json:"gameType"`
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[0]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// RegisterNodeResponse represents the response from node registration
type RegisterNodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ControllerId             string `json:"controllerId"`
	HeartbeatIntervalSeconds int64  `json:"heartbeatIntervalSeconds"`
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[1]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// NodeResources represents resources available on a node
type NodeResources struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalCpuCores      int32 `json:"totalCpuCores"`
	TotalMemoryMb      int64 `json:"totalMemoryMb"`
	TotalStorageMb     int64 `json:"totalStorageMb"`
	AvailableCpuCores  int32 `json:"availableCpuCores"`
	AvailableMemoryMb  int64 `json:"availableMemoryMb"`
	AvailableStorageMb int64 `json:"availableStorageMb"`
}

func (x *NodeResources) Reset() {
	*x = NodeResources{}
}

func (x *NodeResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeResources) ProtoMessage() {}

func (x *NodeResources) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[2]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// NodeEvent represents an event from a node
type NodeEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId        string           `json:"nodeId"`
	Type          EventType        `json:"type"`
	Timestamp     int64            `json:"timestamp"`
	ServerStatus  *ServerStatus    `json:"serverStatus,omitempty"`
	Metrics       *MetricsSnapshot `json:"metrics,omitempty"`
	FileResult    *FileOpResult    `json:"fileResult,omitempty"`
	CommandResult *CommandResult   `json:"commandResult,omitempty"`
}

func (x *NodeEvent) Reset() {
	*x = NodeEvent{}
}

func (x *NodeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeEvent) ProtoMessage() {}

func (x *NodeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[3]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// ControllerCommand represents a command from the controller
type ControllerCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommandId      string             `json:"commandId"`
	Type           CommandType        `json:"type"`
	Timestamp      int64              `json:"timestamp"`
	InitializeNode *InitializeNodeCmd `json:"initializeNode,omitempty"`
	CreateServer   *CreateServerCmd   `json:"createServer,omitempty"`
	StartServer    *StartServerCmd    `json:"startServer,omitempty"`
	StopServer     *StopServerCmd     `json:"stopServer,omitempty"`
	DeleteServer   *DeleteServerCmd   `json:"deleteServer,omitempty"`
	FileList       *FileListCmd       `json:"fileList,omitempty"`
	FileCreate     *FileCreateCmd     `json:"fileCreate,omitempty"`
	FileDelete     *FileDeleteCmd     `json:"fileDelete,omitempty"`
	FileRename     *FileRenameCmd     `json:"fileRename,omitempty"`
	FileMove       *FileMoveCmd       `json:"fileMove,omitempty"`
	FileCopy       *FileCopyCmd       `json:"fileCopy,omitempty"`
	FileWrite      *FileWriteCmd      `json:"fileWrite,omitempty"`
	FileRead       *FileReadCmd       `json:"fileRead,omitempty"`
	FileZip        *FileZipCmd        `json:"fileZip,omitempty"`
	FileUnzip      *FileUnzipCmd      `json:"fileUnzip,omitempty"`
	FileExists     *FileExistsCmd     `json:"fileExists,omitempty"`
	FileMkdir      *FileMkdirCmd      `json:"fileMkdir,omitempty"`
}

func (x *ControllerCommand) Reset() {
	*x = ControllerCommand{}
}

func (x *ControllerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerCommand) ProtoMessage() {}

func (x *ControllerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[4]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// GetInitializeNode returns the InitializeNode command if present
func (c *ControllerCommand) GetInitializeNode() *InitializeNodeCmd {
	if c != nil {
		return c.InitializeNode
	}
	return nil
}

// GetCreateServer returns the CreateServer command if present
func (c *ControllerCommand) GetCreateServer() *CreateServerCmd {
	if c != nil {
		return c.CreateServer
	}
	return nil
}

// GetStartServer returns the StartServer command if present
func (c *ControllerCommand) GetStartServer() *StartServerCmd {
	if c != nil {
		return c.StartServer
	}
	return nil
}

// GetStopServer returns the StopServer command if present
func (c *ControllerCommand) GetStopServer() *StopServerCmd {
	if c != nil {
		return c.StopServer
	}
	return nil
}

// GetDeleteServer returns the DeleteServer command if present
func (c *ControllerCommand) GetDeleteServer() *DeleteServerCmd {
	if c != nil {
		return c.DeleteServer
	}
	return nil
}

// GetFileList returns the FileList command if present
func (c *ControllerCommand) GetFileList() *FileListCmd {
	if c != nil {
		return c.FileList
	}
	return nil
}

// GetFileCreate returns the FileCreate command if present
func (c *ControllerCommand) GetFileCreate() *FileCreateCmd {
	if c != nil {
		return c.FileCreate
	}
	return nil
}

// GetFileDelete returns the FileDelete command if present
func (c *ControllerCommand) GetFileDelete() *FileDeleteCmd {
	if c != nil {
		return c.FileDelete
	}
	return nil
}

// GetFileRename returns the FileRename command if present
func (c *ControllerCommand) GetFileRename() *FileRenameCmd {
	if c != nil {
		return c.FileRename
	}
	return nil
}

// GetFileMove returns the FileMove command if present
func (c *ControllerCommand) GetFileMove() *FileMoveCmd {
	if c != nil {
		return c.FileMove
	}
	return nil
}

// GetFileCopy returns the FileCopy command if present
func (c *ControllerCommand) GetFileCopy() *FileCopyCmd {
	if c != nil {
		return c.FileCopy
	}
	return nil
}

// GetFileWrite returns the FileWrite command if present
func (c *ControllerCommand) GetFileWrite() *FileWriteCmd {
	if c != nil {
		return c.FileWrite
	}
	return nil
}

// GetFileRead returns the FileRead command if present
func (c *ControllerCommand) GetFileRead() *FileReadCmd {
	if c != nil {
		return c.FileRead
	}
	return nil
}

// GetFileZip returns the FileZip command if present
func (c *ControllerCommand) GetFileZip() *FileZipCmd {
	if c != nil {
		return c.FileZip
	}
	return nil
}

// GetFileUnzip returns the FileUnzip command if present
func (c *ControllerCommand) GetFileUnzip() *FileUnzipCmd {
	if c != nil {
		return c.FileUnzip
	}
	return nil
}

// GetFileExists returns the FileExists command if present
func (c *ControllerCommand) GetFileExists() *FileExistsCmd {
	if c != nil {
		return c.FileExists
	}
	return nil
}

// GetFileMkdir returns the FileMkdir command if present
func (c *ControllerCommand) GetFileMkdir() *FileMkdirCmd {
	if c != nil {
		return c.FileMkdir
	}
	return nil
}

// InitializeNodeCmd contains parameters for initializing a node
type InitializeNodeCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameType string `json:"gameType"`
}

func (x *InitializeNodeCmd) Reset() {
	*x = InitializeNodeCmd{}
}

func (x *InitializeNodeCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeNodeCmd) ProtoMessage() {}

func (x *InitializeNodeCmd) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[5]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// CreateServerCmd contains parameters for creating a server
type CreateServerCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId string        `json:"serverId"`
	GameType string        `json:"gameType"`
	Config   *ServerConfig `json:"config"`
}

func (x *CreateServerCmd) Reset() {
	*x = CreateServerCmd{}
}

func (x *CreateServerCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerCmd) ProtoMessage() {}

func (x *CreateServerCmd) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[6]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// StartServerCmd contains parameters for starting a server
type StartServerCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId string `json:"serverId"`
}

func (x *StartServerCmd) Reset() {
	*x = StartServerCmd{}
}

func (x *StartServerCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServerCmd) ProtoMessage() {}

func (x *StartServerCmd) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[7]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// StopServerCmd contains parameters for stopping a server
type StopServerCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId string `json:"serverId"`
}

func (x *StopServerCmd) Reset() {
	*x = StopServerCmd{}
}

func (x *StopServerCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopServerCmd) ProtoMessage() {}

func (x *StopServerCmd) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[8]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// DeleteServerCmd contains parameters for deleting a server
type DeleteServerCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId string `json:"serverId"`
}

func (x *DeleteServerCmd) Reset() {
	*x = DeleteServerCmd{}
}

func (x *DeleteServerCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerCmd) ProtoMessage() {}

func (x *DeleteServerCmd) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[9]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// ServerConfig contains configuration for a game server
type ServerConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string            `json:"name"`
	Version    string            `json:"version"`
	Settings   map[string]string `json:"settings"`
	MaxPlayers int32             `json:"maxPlayers"`
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[10]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// ServerStatus represents the status of a game server
type ServerStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId string      `json:"serverId"`
	State    ServerState `json:"state"`
}

func (x *ServerStatus) Reset() {
	*x = ServerStatus{}
}

func (x *ServerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatus) ProtoMessage() {}

func (x *ServerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[11]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// MetricsSnapshot represents a snapshot of node metrics
type MetricsSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId             string  `json:"nodeId"`
	CpuUsagePercent    float32 `json:"cpuUsagePercent"`
	MemoryUsagePercent float32 `json:"memoryUsagePercent"`
	Timestamp          int64   `json:"timestamp"`
}

func (x *MetricsSnapshot) Reset() {
	*x = MetricsSnapshot{}
}

func (x *MetricsSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsSnapshot) ProtoMessage() {}

func (x *MetricsSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[12]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// File Commands

// FileListCmd contains parameters for listing files
type FileListCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path      string `json:"path"`
	Recursive bool   `json:"recursive"`
}

func (x *FileListCmd) Reset() {
	*x = FileListCmd{}
}

func (x *FileListCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListCmd) ProtoMessage() {}

func (x *FileListCmd) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[13]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// FileCreateCmd contains parameters for creating a file
type FileCreateCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path        string `json:"path"`
	IsDirectory bool   `json:"isDirectory"`
}

func (x *FileCreateCmd) Reset() {
	*x = FileCreateCmd{}
}

func (x *FileCreateCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileCreateCmd) ProtoMessage() {}

func (x *FileCreateCmd) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[14]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// FileDeleteCmd contains parameters for deleting a file
type FileDeleteCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path      string `json:"path"`
	Recursive bool   `json:"recursive"`
}

func (x *FileDeleteCmd) Reset() {
	*x = FileDeleteCmd{}
}

func (x *FileDeleteCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDeleteCmd) ProtoMessage() {}

func (x *FileDeleteCmd) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[15]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// FileRenameCmd contains parameters for renaming a file
type FileRenameCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OldPath string `json:"oldPath"`
	NewPath string `json:"newPath"`
}

func (x *FileRenameCmd) Reset() {
	*x = FileRenameCmd{}
}

func (x *FileRenameCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRenameCmd) ProtoMessage() {}

func (x *FileRenameCmd) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[16]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// FileMoveCmd contains parameters for moving a file
type FileMoveCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourcePath string `json:"sourcePath"`
	DestPath   string `json:"destPath"`
}

func (x *FileMoveCmd) Reset() {
	*x = FileMoveCmd{}
}

func (x *FileMoveCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMoveCmd) ProtoMessage() {}

func (x *FileMoveCmd) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[17]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// FileCopyCmd contains parameters for copying a file
type FileCopyCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourcePath string `json:"sourcePath"`
	DestPath   string `json:"destPath"`
	Recursive  bool   `json:"recursive"`
}

func (x *FileCopyCmd) Reset() {
	*x = FileCopyCmd{}
}

func (x *FileCopyCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileCopyCmd) ProtoMessage() {}

func (x *FileCopyCmd) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[18]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// FileWriteCmd contains parameters for writing a file
type FileWriteCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string `json:"path"`
	Content []byte `json:"content"`
	Append  bool   `json:"append"`
}

func (x *FileWriteCmd) Reset() {
	*x = FileWriteCmd{}
}

func (x *FileWriteCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileWriteCmd) ProtoMessage() {}

func (x *FileWriteCmd) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[19]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// FileReadCmd contains parameters for reading a file
type FileReadCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path   string `json:"path"`
	Offset int64  `json:"offset"`
	Length int64  `json:"length"`
}

func (x *FileReadCmd) Reset() {
	*x = FileReadCmd{}
}

func (x *FileReadCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReadCmd) ProtoMessage() {}

func (x *FileReadCmd) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[20]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// FileZipCmd contains parameters for zipping files
type FileZipCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourcePath string `json:"sourcePath"`
	DestPath   string `json:"destPath"`
	Recursive  bool   `json:"recursive"`
}

func (x *FileZipCmd) Reset() {
	*x = FileZipCmd{}
}

func (x *FileZipCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileZipCmd) ProtoMessage() {}

func (x *FileZipCmd) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[21]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// FileUnzipCmd contains parameters for unzipping files
type FileUnzipCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourcePath string `json:"sourcePath"`
	DestPath   string `json:"destPath"`
}

func (x *FileUnzipCmd) Reset() {
	*x = FileUnzipCmd{}
}

func (x *FileUnzipCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUnzipCmd) ProtoMessage() {}

func (x *FileUnzipCmd) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[22]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// FileExistsCmd contains parameters for checking file existence
type FileExistsCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `json:"path"`
}

func (x *FileExistsCmd) Reset() {
	*x = FileExistsCmd{}
}

func (x *FileExistsCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileExistsCmd) ProtoMessage() {}

func (x *FileExistsCmd) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[23]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// FileMkdirCmd contains parameters for creating a directory
type FileMkdirCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string `json:"path"`
	Parents bool   `json:"parents"`
}

func (x *FileMkdirCmd) Reset() {
	*x = FileMkdirCmd{}
}

func (x *FileMkdirCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMkdirCmd) ProtoMessage() {}

func (x *FileMkdirCmd) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[24]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// FileInfo represents information about a file
type FileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `json:"name"`
	Path         string `json:"path"`
	IsDirectory  bool   `json:"isDirectory"`
	Size         int64  `json:"size"`
	ModifiedTime int64  `json:"modifiedTime"`
	CreatedTime  int64  `json:"createdTime"`
	Permissions  string `json:"permissions"`
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[25]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// FileOpResult represents the result of a file operation
type FileOpResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommandId    string            `json:"commandId"`
	Success      bool              `json:"success"`
	Error        string            `json:"error"`
	ListResult   *FileListResult   `json:"listResult,omitempty"`
	ReadResult   *FileReadResult   `json:"readResult,omitempty"`
	ExistsResult *FileExistsResult `json:"existsResult,omitempty"`
}

func (x *FileOpResult) Reset() {
	*x = FileOpResult{}
}

func (x *FileOpResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOpResult) ProtoMessage() {}

func (x *FileOpResult) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[26]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// FileListResult contains the result of a file list operation
type FileListResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files       []*FileInfo `json:"files"`
	CurrentPath string      `json:"currentPath"`
}

func (x *FileListResult) Reset() {
	*x = FileListResult{}
}

func (x *FileListResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListResult) ProtoMessage() {}

func (x *FileListResult) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[27]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// FileReadResult contains the result of a file read operation
type FileReadResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content   []byte `json:"content"`
	TotalSize int64  `json:"totalSize"`
}

func (x *FileReadResult) Reset() {
	*x = FileReadResult{}
}

func (x *FileReadResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReadResult) ProtoMessage() {}

func (x *FileReadResult) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[28]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// FileExistsResult contains the result of a file exists check
type FileExistsResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exists      bool `json:"exists"`
	IsDirectory bool `json:"isDirectory"`
}

func (x *FileExistsResult) Reset() {
	*x = FileExistsResult{}
}

func (x *FileExistsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileExistsResult) ProtoMessage() {}

func (x *FileExistsResult) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[29]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// CommandResult represents the result of a command
type CommandResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommandId string `json:"commandId"`
	Success   bool   `json:"success"`
	Message   string `json:"message"`
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[30]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// CreateServerRequest represents a request to create a server
type CreateServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId   string        `json:"nodeId"`
	GameType string        `json:"gameType"`
	Config   *ServerConfig `json:"config"`
}

func (x *CreateServerRequest) Reset() {
	*x = CreateServerRequest{}
}

func (x *CreateServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerRequest) ProtoMessage() {}

func (x *CreateServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[31]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// CreateServerResponse represents the response from creating a server
type CreateServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success  bool   `json:"success"`
	ServerId string `json:"serverId"`
	Message  string `json:"message"`
}

func (x *CreateServerResponse) Reset() {
	*x = CreateServerResponse{}
}

func (x *CreateServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerResponse) ProtoMessage() {}

func (x *CreateServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[32]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// DeleteServerRequest represents a request to delete a server
type DeleteServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId string `json:"serverId"`
}

func (x *DeleteServerRequest) Reset() {
	*x = DeleteServerRequest{}
}

func (x *DeleteServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerRequest) ProtoMessage() {}

func (x *DeleteServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[33]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// DeleteServerResponse represents the response from deleting a server
type DeleteServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `json:"success"`
	Message string `json:"message"`
}

func (x *DeleteServerResponse) Reset() {
	*x = DeleteServerResponse{}
}

func (x *DeleteServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerResponse) ProtoMessage() {}

func (x *DeleteServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[34]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// StartServerRequest represents a request to start a server
type StartServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId string `json:"serverId"`
}

func (x *StartServerRequest) Reset() {
	*x = StartServerRequest{}
}

func (x *StartServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServerRequest) ProtoMessage() {}

func (x *StartServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[35]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// StartServerResponse represents the response from starting a server
type StartServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `json:"success"`
	Message string `json:"message"`
}

func (x *StartServerResponse) Reset() {
	*x = StartServerResponse{}
}

func (x *StartServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServerResponse) ProtoMessage() {}

func (x *StartServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[36]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// StopServerRequest represents a request to stop a server
type StopServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId string `json:"serverId"`
}

func (x *StopServerRequest) Reset() {
	*x = StopServerRequest{}
}

func (x *StopServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopServerRequest) ProtoMessage() {}

func (x *StopServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[37]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// StopServerResponse represents the response from stopping a server
type StopServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `json:"success"`
	Message string `json:"message"`
}

func (x *StopServerResponse) Reset() {
	*x = StopServerResponse{}
}

func (x *StopServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopServerResponse) ProtoMessage() {}

func (x *StopServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[38]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// GetServerStatusRequest represents a request to get server status
type GetServerStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId string `json:"serverId"`
}

func (x *GetServerStatusRequest) Reset() {
	*x = GetServerStatusRequest{}
}

func (x *GetServerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerStatusRequest) ProtoMessage() {}

func (x *GetServerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[39]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// GetServerStatusResponse represents the response from getting server status
type GetServerStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *ServerStatus `json:"status"`
}

func (x *GetServerStatusResponse) Reset() {
	*x = GetServerStatusResponse{}
}

func (x *GetServerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerStatusResponse) ProtoMessage() {}

func (x *GetServerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[40]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// StreamMetricsRequest represents a request to stream metrics
type StreamMetricsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId     string `json:"nodeId"`
	IntervalMs int64  `json:"intervalMs"`
}

func (x *StreamMetricsRequest) Reset() {
	*x = StreamMetricsRequest{}
}

func (x *StreamMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMetricsRequest) ProtoMessage() {}

func (x *StreamMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[41]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// NodeMetrics represents node metrics
type NodeMetrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId      string  `json:"nodeId"`
	CpuUsage    float32 `json:"cpuUsage"`
	MemoryUsage float32 `json:"memoryUsage"`
	Timestamp   int64   `json:"timestamp"`
}

func (x *NodeMetrics) Reset() {
	*x = NodeMetrics{}
}

func (x *NodeMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMetrics) ProtoMessage() {}

func (x *NodeMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[42]
	if x == nil {
		return nil
	}
	return mi.MessageOf(x)
}

// File type references for protobuf implementation
var file_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 43)

var _ = protoreflect.Name("")
var _ (*FileInfo)
var _ = sync.Mutex{}
